/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import {
  AWS_REGION,
  AWS_USER_POOL_ID,
  AWS_USER_POOL_WEB_CLIENT,
  AWS_OATH_DOMAIN,
  AWS_OATH_USER_SEC_ATTR,
  AWS_GRAPHQL_ENDPOINT,
  AWS_APPSYNC_API_KEY,
  AWS_FED_TARGET,
  AWS_AUTH_SIGN_IN,
  AWS_AUTH_LOGOUT,
} from "@env";

const awsmobile = {
  aws_project_region: AWS_REGION,
  aws_cognito_region: AWS_REGION,
  aws_user_pools_id: AWS_USER_POOL_ID,
  aws_user_pools_web_client_id: AWS_USER_POOL_WEB_CLIENT,
  oauth: {
    domain: AWS_OATH_DOMAIN,
    scope: ["phone", "email", "openid", "profile", AWS_OATH_USER_SEC_ATTR],
    redirectSignIn: AWS_AUTH_SIGN_IN,
    redirectSignOut: AWS_AUTH_LOGOUT,
    responseType: "code",
  },
  federationTarget: AWS_FED_TARGET,
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint: AWS_GRAPHQL_ENDPOINT,
  aws_appsync_region: AWS_REGION,
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: AWS_APPSYNC_API_KEY,
};

export default awsmobile;
